version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-TopS3cret}
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"